-- CreateTable
CREATE TABLE `Metric` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `temperature` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    `ph` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    `tdo` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    `tds` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    `turbidity` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `pondId` INTEGER NOT NULL,
    `deviceId` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Metric` ADD CONSTRAINT `Metric_pondId_fkey` FOREIGN KEY (`pondId`) REFERENCES `Pond`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Metric` ADD CONSTRAINT `Metric_deviceId_fkey` FOREIGN KEY (`deviceId`) REFERENCES `Device`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
